source 'https://rubygems.org'

# Only development dependencies (things your only plugin needs when running in its own workspace) should
# be listed here in the Gemfile
# This gem provides integration with https://coveralls.io/ to monitor
# your application's test coverage
gem 'coveralls', require: false
gem 'byebug'
gem 'origen_doc_helpers'
# Uncomment these if you want to use a visual debugger (e.g. Visual Studio Code) to debug your app
#gem 'ruby-debug-ide'
#gem 'debase'
#
# Specify your gem's runtime dependencies in tester_std_lib.gemspec
# THIS LINE SHOULD BE LEFT AT THE END
gemspec
